[features]
seeds = false
[programs.devnet]
firstsolanaproject = "EdoR19BL5QuyeQHZaJWxFSjDzDcg9MWhMXEun8btMhLV"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/solana/id.json"

[scripts]
test = "node tests/firstsolanaproject.js"
