const languages = [
  { key: "abap", text: "abap", value: "abap" },
  { key: "aes", text: "aes", value: "aes" },
  { key: "apex", text: "apex", value: "apex" },
  { key: "azcli", text: "azcli", value: "azcli" },
  { key: "bat", text: "bat", value: "bat" },
  { key: "brainfuck", text: "brainfuck", value: "brainfuck" },
  { key: "c", text: "c", value: "c" },
  { key: "cameligo", text: "cameligo", value: "cameligo" },
  { key: "clike", text: "clike", value: "clike" },
  { key: "clojure", text: "clojure", value: "clojure" },
  { key: "coffeescript", text: "coffeescript", value: "coffeescript" },
  { key: "cpp", text: "cpp", value: "cpp" },
  { key: "csharp", text: "csharp", value: "csharp" },
  { key: "csp", text: "csp", value: "csp" },
  { key: "css", text: "css", value: "css" },
  { key: "dart", text: "dart", value: "dart" },
  { key: "dockerfile", text: "dockerfile", value: "dockerfile" },
  { key: "erlang", text: "erlang", value: "erlang" },
  { key: "fsharp", text: "fsharp", value: "fsharp" },
  { key: "go", text: "go", value: "go" },
  { key: "graphql", text: "graphql", value: "graphql" },
  { key: "handlebars", text: "handlebars", value: "handlebars" },
  { key: "hcl", text: "hcl", value: "hcl" },
  { key: "html", text: "html", value: "html" },
  { key: "ini", text: "ini", value: "ini" },
  { key: "java", text: "java", value: "java" },
  { key: "javascript", text: "javascript", value: "javascript" },
  { key: "json", text: "json", value: "json" },
  { key: "jsx", text: "jsx", value: "jsx" },
  { key: "julia", text: "julia", value: "julia" },
  { key: "kotlin", text: "kotlin", value: "kotlin" },
  { key: "less", text: "less", value: "less" },
  { key: "lex", text: "lex", value: "lex" },
  { key: "livescript", text: "livescript", value: "livescript" },
  { key: "lua", text: "lua", value: "lua" },
  { key: "markdown", text: "markdown", value: "markdown" },
  { key: "mips", text: "mips", value: "mips" },
  { key: "msdax", text: "msdax", value: "msdax" },
  { key: "mysql", text: "mysql", value: "mysql" },
  { key: "nginx", text: "nginx", value: "nginx" },
  { key: "objective-c", text: "objective-c", value: "objective-c" },
  { key: "pascal", text: "pascal", value: "pascal" },
  { key: "pascaligo", text: "pascaligo", value: "pascaligo" },
  { key: "perl", text: "perl", value: "perl" },
  { key: "pgsql", text: "pgsql", value: "pgsql" },
  { key: "php", text: "php", value: "php" },
  { key: "plaintext", text: "plaintext", value: "plaintext" },
  { key: "postiats", text: "postiats", value: "postiats" },
  { key: "powerquery", text: "powerquery", value: "powerquery" },
  { key: "powershell", text: "powershell", value: "powershell" },
  { key: "pug", text: "pug", value: "pug" },
  { key: "python", text: "python", value: "python" },
  { key: "r", text: "r", value: "r" },
  { key: "razor", text: "razor", value: "razor" },
  { key: "redis", text: "redis", value: "redis" },
  { key: "redshift", text: "redshift", value: "redshift" },
  {
    key: "restructuredtext",
    text: "restructuredtext",
    value: "restructuredtext",
  },
  { key: "ruby", text: "ruby", value: "ruby" },
  { key: "rust", text: "rust", value: "rust" },
  { key: "sb", text: "sb", value: "sb" },
  { key: "scala", text: "scala", value: "scala" },
  { key: "scheme", text: "scheme", value: "scheme" },
  { key: "scss", text: "scss", value: "scss" },
  { key: "shell", text: "shell", value: "shell" },
  { key: "sol", text: "sol", value: "sol" },
  { key: "sql", text: "sql", value: "sql" },
  { key: "st", text: "st", value: "st" },
  { key: "stylus", text: "stylus", value: "stylus" },
  { key: "swift", text: "swift", value: "swift" },
  { key: "systemverilog", text: "systemverilog", value: "systemverilog" },
  { key: "tcl", text: "tcl", value: "tcl" },
  { key: "toml", text: "toml", value: "toml" },
  { key: "tsx", text: "tsx", value: "tsx" },
  { key: "twig", text: "twig", value: "twig" },
  { key: "typescript", text: "typescript", value: "typescript" },
  { key: "vb", text: "vb", value: "vb" },
  { key: "vbscript", text: "vbscript", value: "vbscript" },
  { key: "verilog", text: "verilog", value: "verilog" },
  { key: "vue", text: "vue", value: "vue" },
  { key: "xml", text: "xml", value: "xml" },
  { key: "yaml", text: "yaml", value: "yaml" },
];

export default languages;
